<a href="https://colab.research.google.com/github/szymek404/data-sciene-bootcamp/blob/main/01_wprowadzenie/02_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
#tworzymy wektor
v1= np.array([-1,4])
v1

array([-1,  4])

In [6]:
np.linalg.norm(v1) # obliczamy normę/długość wektora

4.123105625617661

In [7]:
#liczymy długość wektroa w przedstrzelni R^n (norma euklidesowa)
v2=np.array([-10,10,13])
np.linalg.norm(v2 ) # długość wektora  w przestrzeni R3 maszynowe uczenie używa kilka set przestrzeni

19.209372712298546

In [9]:
#odległość dwóch punktów 
P= np.array([3,0])
Q= np.array([0,4])
np.linalg.norm(P -Q)

5.0

In [11]:
#odległosć w przestrzeni R^n
P= np.array([3,0, 7])
Q= np.array([0,4, 1])
np.linalg.norm(P-Q)


7.810249675906654

In [12]:
#mnożenie macierzy
# wymiary macierzy  A m x x- m wierszy i n kolumn, oraz mamy macierz B n x p, C= m x p ->>> C = A X B
#Aby pomnożyc dwie macierze LICZBA KOLUMN LEWEJ Macierzyt musi być TA SAMA co w PRAWEJ

In [23]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1,3,4], [1,4,6]])
print(X,'\n')
print(Y)

[[5 3]
 [3 9]] 

[[1 3 4]
 [1 4 6]]


In [27]:
Z= np.dot(X,Y)
Z

array([[ 8, 27, 38],
       [12, 45, 66]])

In [28]:
Z.shape

(2, 3)

In [31]:
X = np.array([[5,3,1], [3,9,1]])
Y = np.array([[1,3,4], [1,4,6], [1,4,5]])
print(X,'\n')
print(Y)

[[5 3 1]
 [3 9 1]] 

[[1 3 4]
 [1 4 6]
 [1 4 5]]


In [32]:
np.dot(X,Y)

array([[ 9, 31, 43],
       [13, 49, 71]])

In [35]:
# WYZNACZNIKI MACIERZY 
B = np.array([[2,4], [-1,3]])

np.linalg.det(B) #linalg- LINELAR ALGERBA


9.999999999999998

In [36]:
#żebv zaokrąglić
round(np.linalg.det(B))

10

In [37]:
#slad macierzy, jesli mamy macierz kwadrotową to jest to suma elementów na przekątnej
B = np.array([[2,4], [-1,3]])
np.trace(B) # zwraca slad

5

In [38]:
#macierz jednostkowa to macierz KWADRATOWA, której wspólczyniki na przekątnej są równe 1 
np.eye(5, dtype='int') #buduje macierz jednostkowąp podajemy tylko wymiar

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [47]:
#Macierz odwrotana, MUSI BYĆ KWADRATOWA< taka macierz  istnieje gdy AB = BA =I (czyli gdy jest jakaś macierz przez któa pomnożymy to otrezymujemy jednostkową)
A= np.array([[2,4],[-1,3]])
A
B= np.linalg.inv(A) #linear algebra inverse- tworzy macierz odwrtoną

np.set_printoptions(precision=4, suppress= True) # to nam ustawia do 4 miejsc po przecinku i nie trzeba ogładac noracji
I = np.dot(A, B)
I

array([[1., 0.],
       [0., 1.]])

In [52]:
#Transponowanie - zamienieniamy kolumny na wiersze, wiersze na kolumny
print(A,'\n')
A.T

[[ 2  4]
 [-1  3]] 



array([[ 2, -1],
       [ 4,  3]])

In [53]:
# ROZWIĄZYWANIE UKŁADÓW RÓWNAŃ
#Jezeli macierz ukąłdu A jest kwadratowa (liczba niewiaodmych= liczb równań), to ozacza ze możemy zrobić 
# AX = B
# A^-1AX = A^-1 B
# X= A^-1 B -->> muismy nzaleść maierz odwrotną do macierzy równań i pomnożyć przez macierz wyrazów wolnych

In [55]:
A = np.array([[2,4],[1,-1]])
B= np.array([[10],[-1]])
B

array([[10],
       [-1]])

In [57]:
A_inv = np.linalg.inv(A)
X= np.dot(A_inv, B)
X

array([[1.],
       [2.]])