<a href="https://colab.research.google.com/github/szymek404/data-sciene-bootcamp/blob/main/01_wprowadzeniev2/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print('hello')
import numpy as np
np.__version__

hello


'1.23.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [5]:
x = np.array([1,3])
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim #wymiar
x.shape
x.size #liczba elementów
x.dtype #typ danych

dtype('int64')

In [11]:
x = np.array([1.2, 1.4, 2.7])
print(x.dtype)

float64


In [15]:
x = np.array ([[1,2,],[-3,1]])
print( x.ndim, x.shape, x.size, x.dtype)

2 (2, 2) 4 int64


In [22]:
x= np.array([[1,4,6],[-1,5,9],[-10, -4, 3],[2,7,3]])
print(x, x.shape, x.ndim)

[[  1   4   6]
 [ -1   5   9]
 [-10  -4   3]
 [  2   7   3]] (4, 3) 2


In [23]:
A = np.array([1,4,2])
A.dtype

dtype('int64')

In [30]:
A = np.array([1.3,4.5,2.6], dtype ='int')
A.dtype

dtype('int64')

In [29]:
A= np.array([True, False])
A.dtype

dtype('bool')

In [33]:
A = np.array([130,45,26], dtype =np.int8) #ustawiamy dtype jako 8 bitów
print(A.dtype,A)

int8 [-126   45   26]


In [35]:
#tworzenie tablic funkcje ktore umożliwajaaautomatyzacje budowania ich

np.zeros(shape=(4,10), dtype= 'int') #tworzy tablice z samych zer domyśli jest float

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
np.ones(shape= (2,5)) # jedynki tutaj np. w obrazie można tło przemnożyć przez 0, 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.full(shape=(3,3),fill_value=  4, dtype='int') # wypełnia cała tablicę daną liczbą

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [39]:
np.arange(10) # generuje dane w postaci np.array to samo range(10) w pythonie

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(start=5, stop=100, step =-10) #pozwala wybrać zakres i krok (może byc ujmeny)

array([], dtype=int64)

In [ ]:
np.arange(start= 0, stop=3, step=0.005)

In [46]:
np.linspace(start= 0, stop=1, num=11)# num mówi o tym ile chcemy elemetnów w przedziale wygenerować równo rozłożonych

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [47]:
A = np.arange(15) #tworzymy elemntów
A.reshape((3,5)) #zmieniamy rozmiar, iloczyn musi dać ilośc elementów

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
A.reshape((5,-1)) # wpisując -1 mówimy mu, zeby sam dobrał dobrą ilość kolumn do podanych wierszy

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [51]:
#PODSTAWOWE OPERACJE NA TABLICACH
A= np.array([3, 3.5, 4, 5])
B= np.array([4, -1, -7.1, 2])
print (A)
print (B)

[3.  3.5 4.  5. ]
[ 4.  -1.  -7.1  2. ]


In [61]:
#możemy dodawać dwie tablice mamy metodę add
np.add(A,B)
np.subtract(A,B) #odejmowanie
np.multiply(A,B)
np.divide(A,B)

array([ 0.75      , -3.5       , -0.56338028,  2.5       ])

In [55]:
#dodajemy tablice rozmiar musi się zgadzać
A + B
A-B #po elementach
A *B
A/B # musimy pamiętać, żeby nie było 0 w tablicy przez którą dzielimy

array([ 0.75      , -3.5       , -0.56338028,  2.5       ])

In [58]:
#chcemy dodać co całej tablicy jakaś stała
A+3 #dodaje 3 do każdego elementu
2*A
abs(A)

array([3. , 3.5, 4. , 5. ])

In [62]:
#Mnożenie macierzowe inne niż zwykłe A*B
X =np.array ([[1,3],[-2,0]])
Y= np.array([[6,0],[-1,2]])
print(X, '\n', Y)

[[ 1  3]
 [-2  0]] 
 [[ 6  0]
 [-1  2]]


In [63]:
#aby zrobić mnożenie macierzowe takie jak w algebrze wiersz x kolumna
print (np.dot(X, Y))
print( X*Y)

[[  3   6]
 [-12   0]]
[[6 0]
 [2 0]]


In [64]:
#to mnożenie macierzowe można zpaisac też tak na konkretnej macierzy używajac metody
#mnozenie macierzy nie jest przemienne!
print(X.dot(Y))
print(Y.dot(X))

[[  3   6]
 [-12   0]]
[[ 6 18]
 [-5 -3]]


In [65]:
X @ Y # mnożenie macierzowe specjalny symbol @


array([[  3,   6],
       [-12,   0]])

In [3]:
np.random.seed(0) #genrator liczb pseudo losowych

In [4]:
  np.random.randn(10) # parametr da tablice 10 losowych elementów  z rozkładu normlanego stand o średniej 0 i odchylenie standardowe 1

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [5]:
np.random.rand(10,4) #kolumny liczba zmiennych, wiersze liczba próbek

array([[0.79172504, 0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835, 0.36371077]])

In [6]:
np.random.rand() #wartość losowa z <0,1>

0.5701967704178796

In [11]:
np.random.randint(10) # zwraca całkowitą mniejsza niż 10
np.random.randint(low=10, high= 101, size =10 ) #zakres i ilośc danych
np.random.choice([1,-1,5,56,92]) #zwróci jeden element z listy GDY POTRZEBUJEMY WYBIERAĆ NIBYLOSOWO
np.random.choice(['go','sr','gg'])

'gg'

In [18]:
data = np.arange(10)
data
np.random.shuffle(data)# to miesza wybiórczo nasze dane i nadpisuję te listę
data

array([7, 1, 5, 4, 0, 8, 2, 9, 3, 6])

In [22]:
#podstawowe funkcje z numpy
np.exp(1) #expoment
np.sqrt(9)#pierwiastek kw ale float
np.all([2,0,-11]) #przchodzi po całej liście/obiektu i bada czy ma wartość logiczną T or F

False

In [23]:
np.any([1,2,2]) # sprawdza czy cokolwiek jest prawdą , np. szukamy wiersza gdzie jest jakaś wartość
bool(0) #zwraca wart logiczną

False

In [28]:
A = np.random.rand(5)
print(A) #zakładamy ze to jest prawdopodobienstwo kklasy dla próbki
#szukamy funckji, która da index gdzie nasza tablica jest największa
np.argmax(A)
np.argmin(A)

[0.69253159 0.72525428 0.50132438 0.95608363 0.6439902 ]


2

In [30]:
np.argsort(A) # sortuje podając index, np. mamy kilka klas i szukamy najwięszkej

array([2, 4, 0, 1, 3])

In [31]:
np.max(A)
np.min(A)
np.mean(A)
np.median(A)
np.std(A) # odchylenie standardowe

0.14751805105732366

In [32]:
#indekoswanie, wycinanie danych
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
#A[idx], A [start:stop], A[:stop], A[start:] możliwe wycinania z minusem od końca
A[2]
A[2:10]
A[:2]
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [36]:
A[[2, 0]] #listę podajac wycinanmy tylko te indexy

array([2, 0])

In [37]:
A[-1]

19

In [40]:
A =A.reshape(4,5)
print(A)
A[:,3] # wycinamy kolumne
A[:,-1] #wycinamy ostatnią

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 4,  9, 14, 19])

In [42]:
#wycinamy fragment to podajemy przedziały
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [50]:
A[1,2]=14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
#iteracja po tablicach
for row in A:
  print(row[0:2]) # chcemy po konkretnym elemeneci

[0 1]
[5 6]
[10 11]
[15 16]


In [51]:
for item in A.flat: #flat pozwala wypłaszczyć tablice, dzięki czemu można iterowac
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [52]:
A # tablica wymiauy 4 na 5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
A.reshape(5,4 )

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [57]:
A.ravel() # wypłaszcza dane przeciwieństwo reshape

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
A.T #transponowanie

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [64]:
#maski logiczne
B= np.arange (start =-10, stop=10, step =0.5)
B= B.reshape(10,-1)
B

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [69]:
#chcemy obczaić gdzie jest ujemne
B>0 # zwraca maskę

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
B[B>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [71]:
#możemy łaczyć warunki
np.bitwise_and(B>-5, B<5) # zwraca maske z warunkami gdzie sa spelnione

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])