<a href="https://colab.research.google.com/github/szymek404/data-sciene-bootcamp/blob/main/wprowadzenie/01numy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__


'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [6]:
x = np.array([1,3,])
x
type(x)

numpy.ndarray

In [9]:
x.ndim


1

In [11]:
x.shape
x.size #liczba elemtnow

2

In [12]:
x.dtype #sprawdzamy typ danych i co zabierają

dtype('int64')

In [14]:
x = np.array([1.3,2.3,1.4])

In [15]:
x.dtype

dtype('float64')

In [16]:
#tablice 2D domyslna interpretacja macierzy

In [21]:
y= np.array([[1,3],[1,4]])

In [24]:
y.ndim

2

In [25]:
y.shape

(2, 2)

In [26]:
x= np.array([[1,2,4,5],[1,3,4,5]])

In [27]:
x.shape

(2, 4)

In [4]:
# macierze trzy wymairowe 3D (dane i obraz)
x= np.array(
    [[[1, 4, 7],
     [3, 8, 2]],
     
     [[4, 2, 7],
      [4, 2, 1]],
     
     [[3, 4, 5],
      [3, 6, 8]]]
)
x

array([[[1, 4, 7],
        [3, 8, 2]],

       [[4, 2, 7],
        [4, 2, 1]],

       [[3, 4, 5],
        [3, 6, 8]]])

In [37]:
x.ndim

3

In [36]:
x.shape

(3, 2, 3)

In [10]:
 A = np.array([1.0,2.3,3.3], dtype='int') #możemy ustawic typ danych
 A.dtype

dtype('int64')

In [14]:
A= np.array([True, False])
A.dtype

dtype('bool')

In [17]:
A = np.array([24,120,230], dtype= np.int8) # do obrazó żeby mniej zajomowała w pamięcie jak damu uint to jest unsigh int od 0 do 255
A.dtype

dtype('int8')

In [20]:
 np.zeros(shape=(4,10),dtype=int) #tablica zawalona zerami o dowolnbym kształcie np gdy chgcemy maski do zdjęć

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(shape=(3,5), dtype =int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
A = np.array([2,-3,1,4])
B= np.array([3,-1,3,2])
print(A, B)

In [11]:
A*B # mnożenie dodawania i odejmowanie jest wykonywane po elementach, przy dzieleniu jest zawsze float

array([6, 3, 3, 8])

In [13]:
np.add(A, B)
np.subtract(A,B)

array([-1, -2, -2,  2])

In [14]:
np.multiply(A,B)

array([6, 3, 3, 8])

In [15]:
np.subtract(A,B)

array([-1, -2, -2,  2])

In [21]:
#MNOŻENIE MACIERZOWE 
X= np.array([[1,3], [-2, 2]])
Y= np.array([[0,2], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  2]] 

[[ 0  2]
 [-1  2]]


In [22]:
X*Y

array([[0, 6],
       [2, 4]])

In [23]:
np.dot(X,Y)

array([[-3,  8],
       [-2,  0]])

In [24]:
X.dot(Y) #mnożenie macierzy nie jest przemienne!!

array([[-3,  8],
       [-2,  0]])

In [25]:
X @ Y #specjalny symbol

array([[-3,  8],
       [-2,  0]])

In [28]:
np.random.seed(0) #liczby psedulosowe ustawiamy ziarno losowania, tak żeby wynik był powtarzalny

In [30]:
np.random.randn() #losowy rozkład normalny, zwaraca losową wartośc z rozkładu normlane=go

1.764052345967664

In [31]:
np.random.randn(10) #TABLICA wskazujaca 10  losowo wybranych elementów z rozkładu normlanego standardowego (czyli srednia 0 i odchylenie sand. 1)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [32]:
np.random.randn(10,4) #możemy tak zorbić histogramy 4- liczba kolumn,zmiennych; 10 -liczba propbek)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [34]:
#rozkład jednosajny na przedziale, zwraca =wattość losową z zbioru (0,1)
np.random.rand() #działa tak samo jak jak np.random.randn
np.random.rand(5,2)

array([[0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779]])

In [36]:
# zwraca losową liczbę nieujemną całkowitą mniejsza od 10
np.random.randint(10)

7

In [37]:
np.random.randint(low=10, high= 101, size=5)      #low i high to jakby zakres przeziału z którego losujemy. parametr size daje to ile danyuch chemy 

array([69, 12, 72, 45, 77])

In [39]:
np.random.choice([4,2,1,34,5,2,5,]) #funkcja wybiera randomowo jeden element z obiektu interowalnego 

5

In [52]:
np.random.choice(['py','jaaa','sql']) # mozńa też teskt losowy wybrać

'py'

In [54]:
data = np.arange(10) # funckja arange tworzy listę liczb całkowitych po koleji od 0
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# gdy chcemy mieć przetasowane dane to jest funkcja shuiffle
np.random.shuffle(data) #zmienia od razu zmianną data nie trzeba przypisywać
data

array([2, 1, 4, 9, 8, 5, 7, 3, 0, 6])

In [58]:
#podstawowe funkcje w numpy
np.exp(1) #zwraca exponent 
np.sqrt(9) #zwraca pierwiastek kwadratowy , zawsze foat  zwraca

3.0

In [61]:
np.all([0,3,4,6]) #f all przechodiz po obiekcie iterowalnym i patrzy czy każdy element zwraca false czy true, jak kazdy zwruci true to funkcja zwraca true

False

In [62]:
np.any([0,0,0]) # sprawdza czy ktorykolwiek obiekt jest prawdą , FAŁSZ =0 ,czasem szukamy wiuersza z jakąś wartoscią

False

In [63]:
bool(0) #funckja zwraca wartośc logiczną

False

In [78]:
A= np.random.rand(5) # zakładamy ze to prawdopodobieństwo otrzymamania kalsy dla danej próbki probelm klasyfikacji
A
#musimy znaleść ideks gdzie dostaniemy największą wartość

array([0.5356328 , 0.58990998, 0.73012203, 0.311945  , 0.39822106])

In [82]:
np.argmax(A) #pokazuje indeks najwiękej wartości
np.argmin(A) # najmnijesza wartość

3

In [80]:
A[np.argmax(A)] #wycinamy największa wartości

0.7301220295167696

In [83]:
np.argsort(A) # sortuje elementy odająć indeksy, od najmnijeszej do największej, np pry prawdopodobienstwie jak chcemy wziąc  3 najbardziej prawd. klasy

array([3, 4, 0, 1, 2])

In [84]:
np.max(A)
np.min(A) #wartośći największe i najmniejsze
np.mean(A) #srednia
np.median(A) # mediana
np.std(A) # odchylenie standardowe

0.14640119211997493

In [85]:
#IDEKSOWANIE< wycienanie danych 
B= np.arange(20)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [86]:
#tak można wycinać - konkretny ideks A[idx]; Przedział ideksów A[start:stop]; Konkretny Koniec  A[:stop];    Konkrenty Początek A[start:]

In [94]:
B[2:7]
B[:9] # mozną tez ideksowac od końca strosując liczby ujemne 
print(B[-6:-1])

[14 15 16 17 18]


In [100]:
B= B.reshape(4,5)
B


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [101]:
B[0,:]

array([0, 1, 2, 3, 4])

In [99]:
B[:,1] #wycinay kolumne

array([ 1,  6, 11, 16])

In [102]:
B[1,1]

6

In [105]:
B[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [110]:
B[1,2]= 14  #wycina nam 7 i zamienia na 14
A

array([0.5356328 , 0.58990998, 0.73012203, 0.311945  , 0.39822106])

In [ ]:
#ITERACJA PO TABLICACH

In [120]:
A = np.arange(20, dtype = int)
A= A.reshape(4,5) #co zrobić jak mam 15 elemtów i chcę dodać 0 tam gdzie nie am nic
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [123]:
for row in A:
  print(row[1:4])

[1 2 3]
[6 7 8]
[11 12 13]
[16 17 18]


In [124]:
#po każdym elemencje używami flat co wypłaszcza talice i możemy itrerować element po elemenie

for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [125]:
#ZMIANA rozmiaru tablice
A.shape

(4, 5)

In [126]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [127]:
#metoda ravel jest ODWROTNA DO RESHAPE
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [128]:
#transponowanie tablicy robimy tak 
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [137]:
# Maski logiczne
A =np.arange(start= -10, stop=10, step =0.5)
A = A.reshape(10,-1) # JAK  W RESHAPE DAMY -1 to samo liczy ile kolumn 
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [138]:
#chcemy wiedzieć gdzie są liczby ujemne, możemy to sprawdzić czymś takim A>0
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [140]:
A[A>0] # dostajemy tylko to co jest dodanie i wartość True

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [141]:
A[A>-5 and A< 5] # tak nie wolno zrobić

ValueError: ignored

In [142]:
np.bitwise_and(A>-5, A<5) #tutaj musimy użyć tej fukncji bo tak

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [144]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [145]:
#mamy też not or itp czyli logike

np.bitwise_or( A<- 5, A >5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])