<a href="https://colab.research.google.com/github/szymek404/data-sciene-bootcamp/blob/main/wprowadzenie/statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
#funkcje statystyczne 
price = np.array([[2.4, 2.8,1.9, 2.6, 100 ],
                 [2.5, 3, 1.7 ,2.2, 200],
                 [2.2, 3.4,2.2 ,3.2, 150]])
print(price)

[[  2.4   2.8   1.9   2.6 100. ]
 [  2.5   3.    1.7   2.2 200. ]
 [  2.2   3.4   2.2   3.2 150. ]]


In [6]:
#chemy pokazać funkcje sum
price.sum() #suma wszystkich elementów

480.09999999999997

In [7]:
#chgemy policzyc sume w kolumnie lub w wierszy
price.sum(axis=0) # gdy axis jest na o otrzymujemy sume poszególnych kolumn

array([  7.1,   9.2,   5.8,   8. , 450. ])

In [8]:
#gdy axis na 1 sumujemy po wiuerszach
price.sum(axis=1)

array([109.7, 209.4, 161. ])

In [9]:
np.min(price) #zwraca minimum


1.7

In [10]:
# minimuym z kokrentej kolyumny uzywamy acxis
np.min(price, axis=0)

array([  2.2,   2.8,   1.7,   2.2, 100. ])

In [12]:
# mediana 
np.median(price)

2.6

In [13]:
#srednia po kolumnach
np.mean(price, axis =0)

array([  2.36666667,   3.06666667,   1.93333333,   2.66666667,
       150.        ])

In [15]:
#odchylenie standratowe = standrt deviation
np.std(price, axis= 0)

array([ 0.12472191,  0.24944383,  0.20548047,  0.41096093, 40.82482905])

In [16]:
# wariancja -> var

In [20]:
np.set_printoptions(precision= 2, suppress = True )
np.var(price, axis=0)

array([   0.02,    0.06,    0.04,    0.17, 1666.67])